openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8085
    description: Generated server url
paths:
  /enciclopedia/medicinale/nuovo:
    post:
      tags:
        - medicinale-controller
      operationId: addMedicinale
      parameters:
        - name: params
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/MedicinaleParams'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoMedicinaleDto'
  /enciclopedia/medicinale/modifica-info/{id}:
    post:
      tags:
        - medicinale-controller
      operationId: modificaMedicinale
      parameters:
        - name: idMedicinale
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: params
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/MedicinaleParams'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoMedicinaleDto'
  /enciclopedia/medicinale/info:
    get:
      tags:
        - medicinale-controller
      operationId: getInfoMedicinale
      parameters:
        - name: nomeMedicinale
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoMedicinaleDto'
  /enciclopedia/medicinale/all:
    get:
      tags:
        - medicinale-controller
      operationId: getAllMedicinali
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoListMedicinaleDto'
  /enciclopedia/medicinale/{id}:
    delete:
      tags:
        - medicinale-controller
      operationId: deleteMedicinaleId
      parameters:
        - name: idMedicinale
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
components:
  schemas:
    MedicinaleParams:
      type: object
      properties:
        nome:
          type: string
        descrizione:
          type: string
        dosaggio:
          type: string
    Esito:
      type: object
      properties:
        codRet:
          type: string
          enum:
            - OK
            - WARNING
            - KO
        operationId:
          type: string
        messaggi:
          type: array
          items:
            $ref: '#/components/schemas/Messaggio'
    GenericResponseDtoMedicinaleDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          $ref: '#/components/schemas/MedicinaleDto'
    MedicinaleDto:
      type: object
      properties:
        idMedicinale:
          type: integer
          format: int32
        nome:
          type: string
        descrizione:
          type: string
        dosaggio:
          type: string
    Messaggio:
      type: object
      properties:
        severita:
          type: string
          enum:
            - INFO
            - WARNING
            - ERROR
            - PROPAGATED
        codMsg:
          type: string
        parametri:
          type: array
          items:
            $ref: '#/components/schemas/Parametro'
    Parametro:
      type: object
      properties:
        nome:
          type: string
        valore:
          type: string
    GenericResponseDtoListMedicinaleDto:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: array
          items:
            $ref: '#/components/schemas/MedicinaleDto'
    GenericResponseDtoString:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: string
