openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8083
    description: Generated server url
paths:
  /ms-pazienti/messagistica/ricevi-medico:
    get:
      tags:
        - pazienti-messaggistica-controller
      summary: Ricevi messaggio dal robot medico
      description: Ricevi messaggio dal robot medico
      operationId: msPazienteRiceviMessaggioMedico
      parameters:
        - name: messaggio
          in: query
          description: Messaggio da inviare
          required: false
          schema:
            type: string
            description: Messaggio da inviare
            example: Ciao
          example: Ciao
        - name: livelloUrgenza
          in: query
          description: Livello di urgenza del messaggio da inviare
          required: false
          schema:
            type: string
            description: Livello di urgenza del messaggio da inviare
            example: LOW
          example: LOW
      responses:
        '200':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '400':
          description: Errore elaborazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /ms-pazienti/messagistica/ricevi-infermiere:
    get:
      tags:
        - pazienti-messaggistica-controller
      summary: Ricevi messaggio dal robot infermiere
      description: Ricevi messaggio dal robot infermiere
      operationId: msPazienteRiceviMessaggioInfermiere
      parameters:
        - name: messaggio
          in: query
          description: Messaggio da inviare
          required: false
          schema:
            type: string
            description: Messaggio da inviare
            example: Ciao
          example: Ciao
        - name: livelloUrgenza
          in: query
          description: Livello di urgenza del messaggio da inviare
          required: false
          schema:
            type: string
            description: Livello di urgenza del messaggio da inviare
            example: LOW
          example: LOW
      responses:
        '200':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '400':
          description: Errore elaborazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /ms-pazienti/messagistica/invio-medico:
    get:
      tags:
        - pazienti-messaggistica-controller
      summary: Invio messaggio al robot medico
      description: Invio messaggio al robot medico
      operationId: msPazienteInvioMessaggioMedico
      parameters:
        - name: messaggio
          in: query
          description: Messaggio da inviare
          required: false
          schema:
            type: string
            description: Messaggio da inviare
            example: Ciao
          example: Ciao
        - name: livelloUrgenza
          in: query
          description: Livello di urgenza del messaggio da inviare
          required: false
          schema:
            type: string
            description: Livello di urgenza del messaggio da inviare
            example: LOW
          example: LOW
      responses:
        '200':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '400':
          description: Errore elaborazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
  /ms-pazienti/messagistica/invio-infermiere:
    get:
      tags:
        - pazienti-messaggistica-controller
      summary: Invio messaggio al robot infermiere
      description: Invio messaggio al robot infermiere
      operationId: msPazienteInvioMessaggioInfermiere
      parameters:
        - name: messaggio
          in: query
          description: Messaggio da inviare
          required: false
          schema:
            type: string
            description: Messaggio da inviare
            example: Ciao
          example: Ciao
        - name: livelloUrgenza
          in: query
          description: Livello di urgenza del messaggio da inviare
          required: false
          schema:
            type: string
            description: Livello di urgenza del messaggio da inviare
            example: LOW
          example: LOW
      responses:
        '200':
          description: Messaggio inviato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '400':
          description: Errore elaborazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
        '500':
          description: Errore di sistema
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponseDtoString'
components:
  schemas:
    Esito:
      type: object
      properties:
        codRet:
          type: string
          enum:
            - OK
            - WARNING
            - KO
        operationId:
          type: string
        messaggi:
          type: array
          items:
            $ref: '#/components/schemas/Messaggio'
    GenericResponseDtoString:
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/Esito'
        payload:
          type: string
    Messaggio:
      type: object
      properties:
        severita:
          type: string
          enum:
            - INFO
            - WARNING
            - ERROR
            - PROPAGATED
        codMsg:
          type: string
        parametri:
          type: array
          items:
            $ref: '#/components/schemas/Parametro'
    Parametro:
      type: object
      properties:
        nome:
          type: string
        valore:
          type: string
