-- SINTOMI
INSERT INTO sintomo(id_sintomo, nome, descrizione) VALUES 
(1,'Abbassamento della voce',''),
(2,'Abulia',''),
(3,'Acidosi respiratoria',''),
(4,'Acrofobia',''),
(5,'Addome Acuto',''),
(6,'Afagia',''),
(7,'Affaticamento oculare',''),
(8,'Agorafobia',''),
(9,'Alessitimia',''),
(10,'Alitosi',''),
(11,'Alterazioni del ciclo mestruale',''),
(12,'Amenorrea',''),
(13,'Anemia',''),
(14,'Angoscia',''),
(15,'Anoressia',''),
(16,'Ansia anticipatoria',''),
(17,'Ansia da prestazione',''),
(18,'Ansia da separazione',''),
(19,'Aritmia',''),
(20,'Arrossamento del volto',''),
(21,'Asfissia',''),
(22,'Astenia',''),
(23,'Atassia',''),
(24,'Atelettasia polmonare',''),
(25,'Atetosi',''),
(26,'Atrofia muscolare',''),
(27,'Atrofia e paralisi muscolare',''),
(28,'Aumento dell''appetito',''),
(29,'Aumento della VES',''),
(30,'Aumento di peso',''),
(31,'Batteriuria',''),
(32,'Bolle',''),
(33,'Brachidattilia',''),
(34,'Brividi',''),
(35,'Bruciore agli occhi',''),
(36,'Bruciore alla bocca',''),
(37,'Bruciore retrosternale',''),
(38,'Bruciori di stomaco',''),
(39,'Capogiri',''),
(40,'Cardiomegalia',''),
(41,'Cardiopalmo',''),
(42,'Catarro',''),
(43,'Chetonemia',''),
(44,'Chetonuria',''),
(45,'Chetosi',''),
(46,'Cianosi',''),
(47,'Claustrofobia',''),
(48,'Coma',''),
(49,'Comportamento impulsivo',''),
(50,'Conati',''),
(51,'Corea',''),
(52,'Crampi muscolari',''),
(53,'Depersonalizzazione',''),
(54,'Depressione',''),
(55,'Derealizzazione',''),
(56,'Diarrea',''),
(57,'Difficoltà di concentrazione',''),
(58,'Diminuita sudorazione',''),
(59,'Discromie cutanee',''),
(60,'Disidratazione',''),
(61,'Disfagia',''),
(62,'Disfunzione erettile',''),
(63,'Dispnea',''),
(64,'Disturbi d''umore',''),
(65,'Disuria: difficoltà a urinare - Minzione dolorosa',''),
(66,'Dito a martello',''),
(67,'Dolicocefalia',''),
(68,'Dolore addominale',''),
(69,'Dolore addominale alla palpazione',''),
(70,'Dolore ai reni',''),
(71,'Dolore al petto',''),
(72,'Dolore al ginocchio',''),
(73,'Dolore all''anca',''),
(74,'Dolore all''inguine',''),
(75,'Dolore all''ombelico',''),
(76,'Dolore alla mammella',''),
(77,'Dolore alla parte alta dell''addome',''),
(78,'Dolore allo sterno',''),
(79,'Dolore al piede',''),
(80,'Dolore al tallone',''),
(81,'Dolore al gomito',''),
(82,'Dolore alla spalla',''),
(83,'Dolore alle braccia',''),
(84,'Dolore associato alla masticazione',''),
(85,'Dolore oculare',''),
(86,'Dolori articolari',''),
(87,'Dolori muscolari',''),
(88,'Ectropion',''),
(89,'Edema',''),
(90,'Edema cerebrale',''),
(91,'Edema della papilla',''),
(92,'Emiparesi',''),
(93,'Empiema pleurico',''),
(94,'Emoftoe',''),
(95,'Emorragia subungueale',''),
(96,'Entropion',''),
(97,'Eosinofilia',''),
(98,'Epatomegalia',''),
(99,'Eritema',''),
(100,'Eruttazione',''),
(101,'Evitamento',''),
(102,'Fame',''),
(103,'Febbre',''),
(104,'Fiato corto',''),
(105,'Fobia Sociale',''),
(106,'Fonofobia',''),
(107,'Formazione di pus',''),
(108,'Formicolio al braccio destro',''),
(109,'Formicolio al braccio sinistro',''),
(110,'Formicolio alla mano destra',''),
(111,'Formicolio alla testa',''),
(112,'Formicolio alle mani',''),
(113,'Fotofobia',''),
(114,'Galattorrea',''),
(115,'Gambe dolenti',''),
(116,'Glicosuria',''),
(117,'Gonfiore articolare',''),
(119,'Gonfiore palpebrale',''),
(120,'Gonfiore della mammella',''),
(121,'Idrocefalo',''),
(122,'Idrope Fetale',''),
(123,'Insonnia',''),
(124,'Insulino Resistenza',''),
(125,'Ipercalcemia',''),
(126,'Ipercapnia',''),
(127,'Ipercolesterolemia',''),
(128,'Iperfagia',''),
(129,'Iperglicemia',''),
(130,'Iperidrosi',''),
(131,'Iperlordosi',''),
(132,'Iperkaliemia',''),
(133,'Iperpnea',''),
(134,'Iperprolattinemia',''),
(135,'Ipertensione',''),
(136,'Ipertensione endocranica',''),
(137,'Ipertrofia dei muscoli accessori della respirazione',''),
(138,'Iperventilazione',''),
(139,'Ipoacusia',''),
(140,'Ipokaliemia',''),
(141,'Ipospadia',''),
(142,'Ipotensione',''),
(143,'Ipotrofia muscolare',''),
(144,'Ipotensione ortostatica',''),
(145,'Ipovolemia',''),
(146,'Irrequietezza',''),
(147,'Irsutismo',''),
(148,'Labbra gonfie',''),
(149,'Lacrimazione',''),
(150,'Letargia',''),
(151,'Leucopenia',''),
(152,'Lingua gonfia',''),
(153,'Livedo reticularis',''),
(154,'Macroglossia',''),
(155,'Magrezza',''),
(156,'Mal di gola',''),
(157,'Mal di schiena',''),
(158,'Mal di testa',''),
(159,'Malocclusione dentale',''),
(160,'Meningismo',''),
(161,'Meteorismo funzionale',''),
(162,'Micrognazia',''),
(163,'Nausea',''),
(164,'Nausea e vomito nelle fasi iniziali della gravidanza',''),
(165,'Nervosismo',''),
(166,'Nicturia',''),
(167,'Nodo alla gola',''),
(168,'Noduli al seno',''),
(169,'Noduli polmonari multipli',''),
(170,'Nodulo',''),
(171,'Nodulo polmonare solitario',''),
(172,'Occhi arrossati',''),
(173,'Odinofagia',''),
(174,'Oliguria',''),
(175,'Onicomadesi',''),
(176,'Ortopnea',''),
(177,'Osteoporosi',''),
(178,'Otalgia',''),
(179,'Otorrea',''),
(180,'Pallore',''),
(181,'Papule',''),
(182,'Paraplegia',''),
(183,'Parestesia',''),
(184,'Pelle della mammella a buccia d''arancia',''),
(185,'Pelle grassa',''),
(186,'Pelle scura',''),
(187,'Pelle secca',''),
(188,'Perdita di peso',''),
(189,'Pesantezza allo stomaco',''),
(190,'Piuria',''),
(191,'Pneumomediastino',''),
(192,'Pneumotorace',''),
(193,'Pollachiuria',''),
(194,'Polso paradosso',''),
(195,'Presenza di un nodulo mammario',''),
(196,'Presincope',''),
(197,'Prognatismo',''),
(198,'Prolasso uterino',''),
(199,'Prurito',''),
(200,'Prurito al naso',''),
(201,'Prurito in testa',''),
(202,'Pustole',''),
(203,'Rabdomiolisi',''),
(204,'Raffreddore',''),
(205,'Ragadi Dita',''),
(206,'Ragadi nelle Mani',''),
(207,'Rantoli',''),
(208,'Raucedine',''),
(209,'Reumatismi',''),
(210,'Respiro sibilante',''),
(211,'Riduzione dei rumori respiratori',''),
(212,'Rientro del capezzolo',''),
(213,'Rigidità articolare',''),
(214,'Ritardo di crescita',''),
(215,'Rigidità muscolare',''),
(216,'Rigidità dei muscoli del dorso e del collo',''),
(217,'Rigurgito acido',''),
(218,'Ritenzione idrica',''),
(219,'Ronchi',''),
(220,'Russare',''),
(221,'Salivazione intensa',''),
(222,'Sangue nella saliva',''),
(223,'Sangue nelle urine',''),
(224,'Schiuma nelle urine',''),
(225,'Seborrea',''),
(226,'Secchezza oculare',''),
(227,'Secrezione oculare',''),
(228,'Secrezioni sierose o di sangue dal capezzolo',''),
(229,'Senso di soffocamento',''),
(230,'Sete',''),
(231,'Sete intensa',''),
(232,'Sindrome nefrosica',''),
(233,'Steatorrea',''),
(234,'Stenosi vertebrale',''),
(235,'Stitichezza',''),
(236,'Stranguria',''),
(237,'Stridore',''),
(238,'Somatizzazione',''),
(239,'Sonnolenza',''),
(240,'Splenomegalia',''),
(241,'Squame sulla pelle',''),
(242,'Stanchezza con spasmi (spasmofilia)',''),
(243,'Stato confusionale',''),
(244,'Stato Vegetativo',''),
(245,'Stranguria',''),
(246,'Sudorazione',''),
(247,'Sudorazioni notturne',''),
(248,'Tachicardia',''),
(249,'Tachipnea',''),
(250,'Tenesmo vescicale',''),
(251,'Tremori',''),
(252,'Trombocitosi',''),
(253,'Tosse',''),
(254,'Torace a botte',''),
(255,'Tricodinia',''),
(256,'Unghie con righe verticali',''),
(257,'Unghie grossolane e opache',''),
(258,'Unghie ondulate',''),
(259,'Vampate di calore',''),
(260,'Versamento pericardico',''),
(261,'Versamento pleurico',''),
(262,'Vescicole',''),
(263,'Vertigini',''),
(264,'Versamento Articolare',''),
(265,'Visione offuscata',''),
(266,'Voce nasale',''),
(267,'Vomito','');